apiVersion: v1
kind: Pod
metadata:
  name: k8s-admin-shell
spec:
  containers:
  - image: fritzduchardt/k8s-admin-shell:latest
    name: k8s-admin-shell
    command:
      - "tail"
      - "-f"
      - "/dev/null"
