apiVersion: v1
kind: Pod
metadata:
  name: k8s-admin-shell
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nodeName }}
  nodeName: {{ .Values.nodeName }}
  {{- end }}
  {{- if .Values.image.pullSecret }}
  imagePullSecrets:
    - name: {{ .Values.image.pullSecret }}
  {{- end }}
  hostPID: {{ .Values.hostPID }}
  containers:
    - image: {{ .Values.image }}
      name: k8s-admin-shell
      securityContext:
        privileged: {{ .Values.privileged }}
        runAsUser: {{ .Values.userId }}
      command:
        - "tail"
        - "-f"
        - "/dev/null"
      resources:
        limits:
          cpu: {{ .Values.cpuLimit }}
          memory: {{ .Values.memoryLimit }}
        requests:
          cpu: {{ .Values.cpuRequest }}
          memory: {{ .Values.memoryRequest }}
