apiVersion: v1
kind: Pod
metadata:
  labels:
    run: k8s-admin-shell
  name: k8s-admin-shell
spec:
  hostPID: true
  containers:
  - image: fritzduchardt/k8s-admin-shell:latest
    securityContext:
      privileged: true
    name: k8s-admin-shell
    command:
      - "tail"
      - "-f"
      - "/dev/null"